<a href="https://colab.research.google.com/github/gemsinlife30/gemcode-demo/blob/main/practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


data = {
    'Student ID': ['S001', 'S002', 'S003', 'S004', 'S005',
                    'S006', 'S007', 'S008', 'S009', 'S010'],
    'Name': ['Aarav Sharma', 'Anisha Raut', 'Bibek Thapa', 'Sneha Gurung',
             'Rohan Karki', 'Priya Shrestha', 'Suman Adhikari', 'Aayusha Lama',
             'Nischal Rai', 'Kritika Bhandari'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male',
               'Female', 'Male', 'Female', 'Male', 'Female'],
    'Science': [85, 92, 74, 89, 68, 95, 81, 77, 88, 91],
    'English': [78, 88, 81, 91, 72, 89, 75, 84, 79, 86],
    'Nepali': [82, 90, 76, 87, 70, 93, 79, 88, 85, 89],
    'Hobbies': ['Cricket', 'Reading', 'Football', 'Dancing', 'Gaming',
                'Painting', 'Photography', 'Singing', 'Cycling', 'Reading']
}

df = pd.DataFrame(data)
print("Step 1: Student DataFrame")
print(df)
marks = df[['Science', 'English', 'Nepali']].to_numpy()

print("\nStep 2: NumPy Properties (marks matrix)")
print("Shape:", marks.shape)
print("Size :", marks.size)
print("Ndim :", marks.ndim)

Step 1: Student DataFrame
  Student ID              Name  Gender  Science  English  Nepali      Hobbies
0       S001      Aarav Sharma    Male       85       78      82      Cricket
1       S002       Anisha Raut  Female       92       88      90      Reading
2       S003       Bibek Thapa    Male       74       81      76     Football
3       S004      Sneha Gurung  Female       89       91      87      Dancing
4       S005       Rohan Karki    Male       68       72      70       Gaming
5       S006    Priya Shrestha  Female       95       89      93     Painting
6       S007    Suman Adhikari    Male       81       75      79  Photography
7       S008      Aayusha Lama  Female       77       84      88      Singing
8       S009       Nischal Rai    Male       88       79      85      Cycling
9       S010  Kritika Bhandari  Female       91       86      89      Reading

Step 2: NumPy Properties (marks matrix)
Shape: (10, 3)
Size : 30
Ndim : 2


In [ ]:
print("\nStep 3: Operations")

print("\nTranspose (subjects as rows):\n", marks.transpose())

print("\nTotal marks per student (Science+English+Nepali):\n",
      marks.sum(axis=1))

print("\nAverage marks per subject:\n",
      marks.mean(axis=0))


Step 3: Operations

Transpose (subjects as rows):
 [[85 92 74 89 68 95 81 77 88 91]
 [78 88 81 91 72 89 75 84 79 86]
 [82 90 76 87 70 93 79 88 85 89]]

Total marks per student (Science+English+Nepali):
 [245 270 231 267 210 277 235 249 252 266]

Average marks per subject:
 [84.  82.3 83.9]


In [ ]:
block_a = marks[:3]
block_b = marks[3:6]

print("\nAddition (block_a + block_b):\n", block_a + block_b)
print("\nSubtraction (block_a - block_b):\n", block_a - block_b)
print("\nElement-wise Multiplication:\n", block_a * block_b)
print("\nMatrix Product (block_a x block_b):\n", np.dot(block_a, block_b))

for name, block in [("block_a", block_a), ("block_b", block_b)]:
    det = np.linalg.det(block)
    print(f"\nDeterminant of {name}:", det)
    if abs(det) > 1e-9:
        print(f"Inverse of {name}:\n", np.linalg.inv(block))
    else:
        print(f"{name} is singular, inverse does not exist")


Addition (block_a + block_b):
 [[174 169 169]
 [160 160 160]
 [169 170 169]]

Subtraction (block_a - block_b):
 [[ -4 -13  -5]
 [ 24  16  20]
 [-21  -8 -17]]

Element-wise Multiplication:
 [[7565 7098 7134]
 [6256 6336 6300]
 [7030 7209 7068]]

Matrix Product (block_a x block_b):
 [[20659 20649 20481]
 [22722 22718 22534]
 [19314 19330 19176]]

Determinant of block_a: 13.9999999999958
Inverse of block_a:
 [[-43.          51.         -14.        ]
 [-23.71428571  28.          -7.57142857]
 [ 67.14285714 -79.5         21.71428571]]

Determinant of block_b: 2584.0000000000027
Inverse of block_b:
 [[ 0.18034056 -0.27863777  0.04102167]
 [ 0.12616099  0.00464396 -0.12151703]
 [-0.30495356  0.28018576  0.08513932]]


In [ ]:
print("\nOptional: One-Hot Encoding (Gender & Hobbies)")

encoded = pd.get_dummies(df, columns=['Gender', 'Hobbies']).astype(
    {col: int for col in pd.get_dummies(df, columns=['Gender', 'Hobbies']).columns
     if pd.get_dummies(df, columns=['Gender', 'Hobbies'])[col].dtype == bool}
)
print(encoded)


Optional: One-Hot Encoding (Gender & Hobbies)
  Student ID              Name  Science  English  Nepali  Gender_Female  \
0       S001      Aarav Sharma       85       78      82              0   
1       S002       Anisha Raut       92       88      90              1   
2       S003       Bibek Thapa       74       81      76              0   
3       S004      Sneha Gurung       89       91      87              1   
4       S005       Rohan Karki       68       72      70              0   
5       S006    Priya Shrestha       95       89      93              1   
6       S007    Suman Adhikari       81       75      79              0   
7       S008      Aayusha Lama       77       84      88              1   
8       S009       Nischal Rai       88       79      85              0   
9       S010  Kritika Bhandari       91       86      89              1   

   Gender_Male  Hobbies_Cricket  Hobbies_Cycling  Hobbies_Dancing  \
0            1                1                0          